### ISSUE TITLE
Is there support for multiple servers?

### ISSUE THREAD

**Issue by emil-nasso** [Namoshek/laravel-redis-sentinel#15]
Hi! :wave:

I looking for some way to connect to a redis sentinel cluster in a laravel project and ran into this package.

There is something I don't understand though.

Is there no way to specify multiple servers? The documentation doesn't hint on how to set that up and looking through the source code I can't really figure it out either.

We are expecting to have three servers running redis sentinel and if one of these are down, we would still want the applications to be able to connect.

Do I understand this right? With this package, you can only specify one server, and if that server is down (but all other servers in the sentinel cluster is up), you won't be able to reach the redis sentinel cluster?

**Comment by Namoshek** [comment]
This package was written with the intention to be used behind a load balancer for Redis Sentinel, i.e. where all Redis Sentinel instances share one IP and failed instances are removed automatically by the load balancer.

If you allow configuring multiple Redis Sentinel instances in the application, you move the responsibility to detect failed instances to the application. In case you have multiple applications with a similar architecture, this means you have the same problem and responsibility over and over again. Therefore it is preferrable to have a load balancer do this for you.

In case of Kubernetes (which is where we have been using this library, but are not anymore due to architectural changes), we've simply used a Service in front of our Redis Sentinel StatefulSet in combination with health checks.
There are many other suitable tools for load balancing and/or virtual IPs though, and you can certainly do the same on a VM or with Docker.

**Comment by emil-nasso** [comment]
@Namoshek Ok. Thanks for the insights. We were considering running sentinel without a load balancer and just letting the application try the other instances, in case one doesn't answer. I see your point, however. We will look into it and consider it. Thanks.

Are you not using the library at all anymore? Are you planning to continue maintain it, adding support for new Laravel and php-versions?

**Comment by Namoshek** [comment]
I think the library is still a dependency of our application and would probably work just fine, but we have configured a different Redis driver at the moment. That's also why the library never made its way to a v1 - I've not enough production-level experience with it so far.

As long as there are no major rewrites required (i.e. when Laravel or the phpredis extension change completely), I will probably support it, yes. The whole library isn't really that big and complex, so this should not be an issue anway.

**Comment by LyKos4** [comment]
So if we are talking for a setup in Kubernetes with 3 sentinel pods , the REDIS_SENTINEL_HOST will be the SENTINEL service while the 
REDIS_SENTINEL_SERVICE will be the redis service?

    'default' => [
        'sentinel_host' => env('REDIS_SENTINEL_HOST', '127.0.0.1'),
        'sentinel_port' => env('REDIS_SENTINEL_PORT', 26379),
        'sentinel_service' => env('REDIS_SENTINEL_SERVICE', 'mymaster'),


With redis service I mean the service that maps to the  redis pods and with sentinel service the one that maps to sentinel pods.
