### ISSUE TITLE
variables clarifications

### ISSUE THREAD

**Issue by LyKos4** [Namoshek/laravel-redis-sentinel#29]
I need some clarifications for the variables used in this setup in kubernetes:

REDIS_SENTINEL_HOST should be one of the 3 (for example) pods of sentinel? 
REDIS_SENTINEL_PORT should be the port of the sentinel service that is setup? Can it be different than 26379?
REDIS_SENTINEL_PASSWORD should be same for redis and sentinel?

**Comment by Namoshek** [comment]
For `REDIS_SENTINEL_HOST` you should use a load balanced endpoint for your Sentinels, e.g. a Kubernetes service that sends traffic to any of the available Sentinels. The `REDIS_SENTINEL_PORT` should then be the port of that service (can be anything, but most times you'd use 26379 unless you have multiple Sentinels).

For connecting to Sentinel, the password defined by `REDIS_SENTINEL_PASSWORD` is used. For the Redis instance that is connected to after looking up the hosts via the Sentinels, `REDIS_PASSWORD` is used. They can be the same, but in my opinion they shouldn't.

In general this library uses variables called `REDIS_SENTINEL_*` when it affects the connection to Redis Sentinel, and variables `REDIS_*` when it affects the connection to Redis itself. The latter only affects the password and database.

**Comment by LyKos4** [comment]
So if I have multiple pods of sentinel but  in a specific service that has one port 26379, should it work?

**Comment by Namoshek** [comment]
Yes, but you should make sure that the service only routes traffic to healthy pods. In other words, you should add health checks (especially a readiness probe) to the Sentinel pods. Otherwise, in case of a failure, the application might connect to a non-responsive Sentinel and will be taken down as well.

**Comment by LyKos4** [comment]
Thank you

**Comment by LyKos4** [comment]
Regarding REDIS_SENTINEL_USERNAME how it used for authentication? Can't we access the data just by the use of a password defined in sentinel statefulset?
Also regarding the REDIS_SENTINEL_PERSISTENT is it a boolean variable? Can't we use a  persistent volume without setting it to true? How exactly is it used?

**Comment by Namoshek** [comment]
The `REDIS_SENTINEL_USERNAME` is optionally, same as `REDIS_SENTINEL_PASSWORD`. If you set only `REDIS_SENTINEL_PASSWORD`, then only the password is passed to the `RedisSentinel` object. If you define also `REDIS_SENTINEL_USERNAME`, then both are passed. You can also just leave the variable empty, we only pass the values if they are a string with a length of 1 or longer.

The `REDIS_SENTINEL_PERSISTENT` is an optional boolean flag which can be used to request a persistent connection to Redis Sentinel. It's a feature of the `phpredis` extension and works similar to persistent connections of other PHP extensions like MySQL. The idea is that connections are kept open by e.g. php-fpm between requests are reused instead of initiating a new connection per request. It has nothing to do with storage.
